# Generated by Django 3.1.4 on 2020-12-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeSaude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da unidade de saúde')),
                ('endereco', models.CharField(max_length=300, verbose_name='endereço')),
                ('uf', models.CharField(max_length=3, verbose_name='Sigla da UF da unidade de saúde (ex: RN, SP, AM, AC...)')),
                ('cidade', models.CharField(max_length=200, verbose_name='Cidade da unidade de saúde')),
            ],
            options={
                'verbose_name': 'Unidade de Saúde',
                'verbose_name_plural': 'Unidades de Saúde',
            },
        ),
    ]
