# Generated by Django 3.1.4 on 2020-12-18 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacinaUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da vacina')),
                ('qt_vacinas', models.BigIntegerField(verbose_name='Quantidade de vacinas')),
                ('qt_vacinas_aplicadas', models.BigIntegerField(verbose_name='Quantidade de vacinas aplicadas')),
                ('unidade_saude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.unidadesaude', verbose_name='Unidade de saude que vai receber as vacinas')),
            ],
            options={
                'verbose_name': 'Vacina da Unidade de Saúde',
                'verbose_name_plural': 'Vacinas da Unidade de Saúde',
            },
        ),
    ]
