# Generated by Django 3.1.4 on 2020-12-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0002_vacinaus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacinaus',
            name='qt_vacinas_aplicadas',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Quantidade de vacinas aplicadas'),
        ),
    ]
