# Generated by Django 3.1.4 on 2020-12-18 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do (a) coordenador (a)')),
                ('username', models.CharField(max_length=200, verbose_name='Apelido do (a) coordenador (a)')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail do (a) coordenador (a)')),
                ('cpf', models.CharField(max_length=25, unique=True, verbose_name='CPF do (a) coordenador (a)')),
                ('cel', models.CharField(max_length=25, verbose_name='Telefone do (a) coordenador (a)')),
            ],
            options={
                'verbose_name': 'Coordenador',
                'verbose_name_plural': 'Coordenadores',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do (a) paciente')),
                ('numero_carteira', models.CharField(max_length=100, null=True, verbose_name='Número da carteirinha do sus')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail do (a) paciente')),
                ('cpf', models.CharField(max_length=25, unique=True, verbose_name='CPF do (a) paciente')),
                ('cel', models.CharField(max_length=25, verbose_name='Telefone do (a) paciente')),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do (a) profissional')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail do (a) profissional')),
                ('cpf', models.CharField(max_length=25, unique=True, verbose_name='CPF do (a) profissional')),
                ('cel', models.CharField(max_length=25, verbose_name='Telefone do (a) profissional')),
            ],
            options={
                'verbose_name': 'Profissional da saúde',
                'verbose_name_plural': 'Profissionais da saúde',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='E-mail do usuário')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Data de Adesão')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Último Login')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Administrador')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superusuário')),
                ('perfil_coordenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.coordenador', verbose_name='Perfil do Coordenador')),
                ('perfil_paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.paciente', verbose_name='Perfil do Paciente')),
                ('perfil_profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.profissional', verbose_name='Perfil do Profissional da Saúde')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
