# Generated by Django 3.1.4 on 2020-12-18 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0002_vacinaus'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='unidade_saude',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativo.unidadesaude', verbose_name='Unidade de saúde onde o profissional trabalha'),
        ),
    ]
