# Generated by Django 3.1.4 on 2020-12-19 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_profissional_unidade_saude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='numero_carteira',
        ),
    ]
