# Generated by Django 3.1.4 on 2020-12-18 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrativo', '0002_vacinaus'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendar_Vacina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateField(auto_now_add=True, verbose_name='Data que foi solicitado')),
                ('data_agendada', models.DateField(verbose_name='Data do agendamento')),
                ('pos_fila', models.BigIntegerField(verbose_name='Posição do paciente na fila')),
                ('turno', models.CharField(blank=True, choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], max_length=100, null=True, verbose_name='Turno da visita')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.paciente', verbose_name='Paciente que agendou')),
                ('unidade_saude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.unidadesaude', verbose_name='Unidade de saúde que foi escolhida')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.vacinaus', verbose_name='Vacina escolhida para aplicação')),
            ],
            options={
                'verbose_name': 'Agendamento da vacina',
                'verbose_name_plural': 'Agendamentos de vacina',
            },
        ),
    ]
