# Generated by Django 3.1.4 on 2020-12-18 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('administrativo', '0002_vacinaus'),
        ('Agendamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agendar_Vacina',
            new_name='AgendarVacina',
        ),
    ]
