# Generated by Django 3.1.4 on 2020-12-18 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0002_vacinaus'),
        ('Agendamento', '0002_auto_20201218_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendarvacina',
            name='turno',
            field=models.CharField(blank=True, choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], max_length=100, null=True, verbose_name='Turno do agendamento'),
        ),
        migrations.CreateModel(
            name='PeriodoVacina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do dia para vacinação')),
                ('turno', models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], max_length=100, verbose_name='Turno disponivel para vacinação')),
                ('unidade_saude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.unidadesaude', verbose_name='Unidade de saúde referente ao periodo de vacina')),
            ],
            options={
                'verbose_name': 'Periodo de vacinação',
                'verbose_name_plural': 'Periodos de vacinação',
            },
        ),
    ]
