# Generated by Django 3.1.4 on 2020-12-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agendamento', '0004_auto_20201219_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendarvacina',
            name='data_solicitacao',
        ),
        migrations.AlterField(
            model_name='agendarvacina',
            name='data_agendada',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Data agendada'),
        ),
    ]
