# Generated by Django 3.1.4 on 2020-12-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agendamento', '0005_auto_20201219_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendarvacina',
            name='sus',
            field=models.BooleanField(default=False, verbose_name='Vacina Aplicada'),
        ),
    ]
