# Generated by Django 3.1.4 on 2020-12-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agendamento', '0006_agendarvacina_sus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendarvacina',
            old_name='sus',
            new_name='vacina_aplicada',
        ),
        migrations.AddField(
            model_name='agendarvacina',
            name='agendamento_stts',
            field=models.BooleanField(default=False, verbose_name='Agendamento Aprovado'),
        ),
    ]
