# Generated by Django 3.1.4 on 2020-12-18 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_profissional_unidade_saude'),
        ('cartaoVacina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacinapaciente',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.paciente', verbose_name='Paciente que tomou a vacina'),
        ),
    ]
